#!/bin/bash
function read_arg()
{

	IFS=' ' read -p "${@}" input

	while [[ -z "$input" ]]
	do
	  IFS=' ' read -p "${@}" input
	done

	echo $input
}

dir_path="/home/shopclues/bin/cred/fqa2.txt"
IFS=' ' cred=($(cat "${dir_path}"))
check=1
folder=""

while : 
	if [[ -z $1 ]]; then
		check=$(read_arg "choose fqa2 branch : 1.admin 2.vendor 3.soa 4.mobile 5.my_account: ")
	else
		check=${1}
	fi
do
	case $check in
		1)
			folder="admin"
			break
			;;
		2)
			folder="vendor"
			break
			;;
		3)
			folder="soa"
			break
			;;
		4)
			folder="mobile"
			break
			;;
		5)
			folder="my_account"
			break
			;;

		*)
			break
			;;
	esac
done

serverConnection ${cred[0]} ${cred[1]} ${cred[2]} ${cred[3]} ${cred[4]} ${cred[5]} ${folder} 
